<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><!-- InstanceBegin template="/Templates/hotsite.dwt.php" codeOutsideHTMLIsLocked="false" -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- InstanceBeginEditable name="doctitle" -->
<title>Viva! HOT! Campaign</title>
<!-- InstanceEndEditable -->
<link href="/campaigns/hot/includes/styles.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="/campaigns/hot/includes/ddtabmenu.css">
<script type="text/javascript" src="/campaigns/hot/includes/ddtabmenu.js">

/***********************************************
* DD Tab Menu script- © Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
***********************************************/

</script>
<script type="text/javascript">

//SYNTAX: ddtabmenu.definemenu("tab_menu_id", integer OR "auto")
ddtabmenu.definemenu("ddtabs1", "auto") //initialize Tab Menu #1 with 1st tab selected
</script>
<!-- InstanceBeginEditable name="head" --><!-- InstanceEndEditable -->
</head>

<body>
<table width="754" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
        <tr valign="top">
          <td width="41" height="41" bgcolor="#990099" class="bgleft"><img src="/campaigns/hot/images/bgtl.jpg" alt="" width="41" height="41"></td>
          <td class="bgtop"><?php include '../includes/menu.php'; ?></td>
          <td width="41" height="41" class="bgright"><img src="/campaigns/hot/images/bgtr.jpg" alt="" width="41" height="41"></td>
        </tr>
      </table>
   </td>
  </tr>
  <tr>
    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="15" class="bgleft">&nbsp;</td>
        <td valign="top" bgcolor="#FFFFFF"><!-- InstanceBeginEditable name="banner" --><img src="/campaigns/hot/images/banner05.jpg" alt="" width="724" height="249"><!-- InstanceEndEditable -->
          <div id="content"><!-- InstanceBeginEditable name="content" -->
            <p align="center"><strong>Contents</strong>: <br>
              <a href="index.php">Overview</a> | 
              <a href="page2.php">Global Warming</a> | 
              <a href="page3.php">Deforestation and Loss of Biodiversity</a> | 
              <a href="page4.php">Overuse of Fresh Water</a> |
              <a href="page5.php">Destruction of the Oceans</a> | 
              <a href="page6.php">Fish Farming</a> | 
              <a href="page7.php">Pollution: <span class="smalltext">Antibiotic Pollution</span></a><span class="smalltext"> | <a href="page8.php">Chemical Pollution</a> | <a href="page9.php">Heavy Metal Pollution</a> | <a href="page9.php">Pesticide Pollution</a></span> |
              <a href="page9a.php">Desertification</a> |
              <a href="page11.php">Bird Flu</a>  |
              <a href="page11.php">Health</a> | <a href="page12.php">References</a></p>
            <h1><strong>Overview</strong></h1>
            <p>When it was founded in 1994, Viva! started campaining on the environment, warning that livestock farming is destroying the Earth. Pick any of the most threatening environmental problems, we said, and you will find farmed animals at the heart of it.</p>
            <p>It was not that we were clairvoyant but that there was a mountain of science available even then to show that the animals used to produce meat, dairy and leather were responsible for a devastating loss of forests, the unrelenting spread of existing deserts and the degradation of fertile land into lifeless dust.</p>
            <p>The facts were clear - farmed animals are also largely responsible for the overuse of fresh water, for the pollution of surface, ground and sea water, for the devastating loss of species and for the bulk of acid rain. Livestock are also major players in the most pressing of all catastrophes – climate change. The concerns which started our campaign have grown much more acute as meat, fish and dairy consumption across the world has increased. </p>
            <p>Much of this evidence was explored in popular but fully-referenced books such as <em>Diet for a New America</em>, <em>Food for a Future, Beyond Beef</em> and Juliet Gellatley’s (Viva!’s Director) <em>The Silent Ark</em> so it wasn’t buried in obscure archives but readily available to all. Governments and their battery of advisers chose to ignore this research almost in its entirety and the outcome is a global crisis that threatens us all.</p>
            <p>The reason why livestock are so damaging to the global environment is their gross inefficiency in converting plant foods into meat. The most inefficient of all are cattle who, for every 17 kilograms of high-quality vegetable protein they eat, produce just one kilogram of meat. The other 16 kilograms is required to maintain their temperature, provide them with energy and fuel their bodily functions or is simply excreted. To a lesser degree it is the same with all other farmed animals. </p>
            <p>In a world which has essentially run out of new sources of agricultural land, it is insane that 70 per cent of all farmed land on the globe is dedicated to rearing animals in an orgy of cruelty and inefficiency that truly boggles the mind. On a vegetarian diet less than half the current agricultural land would be needed – on a vegan diet less than a quarter. </p>
            <p>The current level of meat and dairy consumption as it stands – 55 billion farmed animals were slaughtered worldwide in 2006 - is utterly unsustainable and is destroying the global environment at a scale never previously seen. And yet the two industries are boasting of their plans for future growth. This can only happen by greater intensification into obscene factory farms, more use of chemicals and a destruction of remaining forests and wilderness areas. </p>
            <p>If this happens there is no doubt about the outcome – all the devastating problems highlighted in this report will accelerate, including global warming. The more enlightened in the meat industry are aware of the dangers that will result. “…Nature might be totally unpredictable if knocked out of balance – we are not able to destroy the Earth but we might change the climate in an unpredictable direction, at worst endangering our survival as a species.” That was Europe meat industry vets writing in the 1990s – many more authoritative voices have since echoed their sentiments.&nbsp; </p>
            <p>In 2006, the United Nations Food &amp; Agriculture Organisation (UN FAO) produced an extraordinary report on the devastating effect that animal agriculture is having on the planet (<em>Livestocks’ Long Shadow</em> – environmental issues and options). Running to almost 400 pages with 666 references, it is an extraordinary document and establishes that livestock are one of the greatest threats to the global environment. The quote on the cover of this report illustrates just how seriously the UN FAO regards the situation.</p>
            <p>The detail of their report is extraordinary and it serves no purpose to repeat it all here. It would, however, make a superb adjunct to this report, which draws on research from other sources and attempts to interpret some of the UN’s findings. (View at www.fao.org/newsroom/en/news/2006/1000448/index.html)&nbsp; <a href="http://www.fao.org/newsroom/en/news/2006/1000448/index.html">&nbsp;</a><br>
  &nbsp;&nbsp; <br>
              The same politicians who have historically ignored the environmental impact of livestock by blinding themselves to the science appear to be eager to repeat the process, failing to acknowledge the importance or even existence of the UN FAO’s report. Instead, they flit around the margins of this crisis pretending they have the answers when they have not even identified the problem.</p>
            <p>It is a global calamity and the increasingly desperate wording in scientific reports reflects this but the meat and dairy industries, as far as politicians and the media are concerned, are apparently beyond reproach. Just what a betrayal of the democratic process this amounts to is made clear by my report.</p>
            <p>The tragedy is that livestock are at the heart of all the world’s great environmental catastrophes and currently there appears to be no attempt to rein in the unbridled expansion of the global meat and dairy industry. In fact the opposite is true – it is expanding almost exponentially with massive subsidies to encourage its growth.</p>
            <p>Current obsessions – and rightly so - are with climate change but this has obscured many other environmental disasters that may in the long term create equally devastating problems for life on Earth.&nbsp;&nbsp; </p>
            <p>It is now clear that livestock and industrial fishing are the second biggest source of greenhouse gases from a combination of carbon dioxide produced by meat, fish and dairy production methods, methane from ruminants’ digestion and nitrous oxide from manure. This combination accounts for 18 per cent of global warming compared with 13.5 per cent for the world’s entire transport system – cars, boats, planes, trains, lorries and so on.</p>
            <p>Interestingly, air transport accounts for three per cent of global warming gases yet this is the industry the UK government has chosen to pillory as the unacceptable face of capitalism. It has ignored entirely the role of livestock despite concerns that we are close to – or may have already passed – a point of no return where the world’s complex ecosystems take over and trigger a process known as positive feedback. This is when the globe automatically begins to release its vast deposits of methane and carbon and the phenomenon of global warming becomes unstoppable and uncontrollable. </p>
            <p>No one knows what the long-term effects will be of trashing the planet’s biodiversity – exterminating plants, animals and micro-organisms - in an orgy of vandalism for short-term profit. One thing is certain, it will not be to the benefit of humankind.</p>
            <p>Livestock producers are the driving force behind loss of biodiversity and they can already&nbsp; claim to have driven to the brink of extinction one-third of all amphibians, a fifth of mammals and one-eighth of all birds. This is based on known species and yet it is estimated that 90 per cent of all existing species are unknown and so the true rate of extinction could be 10 times greater than this.</p>
            <p>At the heart of this appalling decline is the trashing of rainforest across the globe by ranchers fuelling the burger boom with cheap beef. Everyone who eats meat or dairy can also claim a stake in the destruction as soya animal feed increasingly becomes the high-protein fodder of choice.</p>
            <p>Some 70 per cent of cleared Amazon rainforest is used for grazing cattle while most of the remaining 30 per cent is used for soya production for animal feed and Europe is one of its most eager importers.</p>
            <p>The trampling of heavy bodies and hard hooves of livestock and their overgrazing are the primary reasons why deserts are remorselessly spreading everywhere, why topsoil is being lost far faster than it can be created, why land is degrading and soil is losing its fertility in almost every region of the world, including the US.</p>
            <p>Arid and semi-arid lands girdle the world and make up one-third of the total land surface. Some 72 per cent are degraded, primarily by grazing animals.<br>
              In the quest for yet more animal protein, the devastation on land extends to the oceans where 82 per cent of species are being fished beyond safe biological limits – they are on the road to extinction. Fish farming – aquaculture - is increasingly being touted as the answer to overfishing. Not only is it not the solution it is a central part of the problem. For every tonne of farmed fish produced, four tonnes of wild-caught fish are killed to provide their food. As the current output of farmed fish is around 40 million tones per year, that’s an awful lot of killing. &nbsp;&nbsp;&nbsp;<br>
              In some ways it feels as though we have all been here before. Although not strictly an environmental concern, the other side of the same livestock coin is the impact that meat and dairy are having on human health in the affluent West. They are the primary cause of the affluent degenerative diseases which destroy the health of most people in the developed world, which place virtually the entire population at risk and which eventually kill most of them.</p>
            <p>Cancer and heart disease are at epidemic proportions, afflicting one in three of the population and increasing remorselessly, as are both types of diabetes (1 and 2), strokes, obesity, Alzheimer’s disease, osteoporosis and gall bladder disease, amongst others. </p>
            <p>Despite official claims to the contrary, we are a seriously ailing population increasingly dependent upon pills, potions and procedures. It is early diagnosis and these interventions which are the primary reasons for increases in longevity. We’re living longer but not healthier and again it is meat and dairy which carry the lion’s share of the blame. </p>
            <p>The science implicating animal products in the West’s health crisis is overwhelming and was brought together in a scientific review by the World Health Organisation (WHO) in 1990. It was unequivocal in its findings, with strong urgings that there should be a fundamental change in the West’s agricultural polices - the marketing of meat and dairy products ended in favour of plant foods.</p>
            <p>It also warned that its recommendations were likely to meet with fierce opposition. In this they were wrong – the report was simply ignored.</p>
            <p>The WHO’s main concerns were over saturated animal fats and cholesterol as well as added fats, salt and sugar. Reporting at the same time, however, was the landmark China Study, the largest epidemiological study ever undertaken. It established that animal protein was even more damaging to health than saturated fat and triggered cancers and raised cholesterol levels and that the damage began at very low intakes.</p>
            <p>This was also ignored. In fact despite the profundity of these findings and the flood of other research which has followed, public health policy has barely been influenced at all. Worse than this, many health authorities, through their nutrition pyramids and recommended food group intakes, have continued advocating meat and dairy products as an essential part of the diet.</p>
            <p>The official diet recommended to those with heart disease still includes white meat and dairy products and reduces the risk of a heart attack by only five per cent. A plant-based diet could take them out of the risk zone entirely and even reverse the damage to their arteries. It begs the question – why is meat so protected?</p>
            <p>We cannot afford a similar bout of political protectionism for the livestock industries where the environment is concerned.</p>
            <p>Added to these degenerative health threats are new, infectious ones, some of which have already revealed themselves whilst we await the arrival of others with trepidation.</p>
            <p>In 1969, the Swann report raised serious concerns about the overuse of antibiotics in intensive (factory) farm systems for disease control and their administration on a daily basis as growth promoters. The fear was that because of bacteria’s ability to develop resistance in animals (and pass on that resistance to other bacteria species), when those&nbsp; bacteria infected humans they would carry their antibiotic resistance with them, resulting in a steadily decreasing choice of drugs with which to treat the infections.</p>
            <p>Two similar but much more recent reports have said much the same thing but far more stridently, warning of an end to all invasive surgery. A return to pre-antibiotic days would have a profound impact on the population and herald the return of widespread infectious diseases.</p>
            <p>While governments have tinkered around with this problem, banning some growth promoting or therapeutic antibiotics here and there, antibiotic use has continued unabated in factory farms – in fact they could not survive without them such is the nature of these cruel and appallingly unhygienic systems.</p>
            <p>What Swann could never have predicted, of course, was the extraordinary increase in global meat and dairy consumption and the concentration of 80 per cent of livestock into crowded, intensive systems. There has been a corresponding explosion in the quantity of antibiotics used and the subsequent development of resistant strains of deadly food poisoning bacteria such as <em>salmonella, campylobacter</em> and <em>E coli</em> 0157.</p>
            <p>Just as concerning is the mutation of superbugs such as MRSA, VRSA and <em>C Difficile</em>, which are killing increasing numbers of people through hospital-acquired infections. In his book, <em>Superbug – Nature’s Revenge</em> (1995), Geoffrey Canon estimated that 60,000 people a year in the US were dying from infections they caught while in hospital.</p>
            <p>At about that time I was researching the US health care system and was advised by a&nbsp; group of doctors not to be admitted to their hospitals if I could possibly avoid it. If I did have to go in, I should have as little done to me as possible and get out as soon as I could. Both these statements were shocking back then but the situation has got a great deal worse since and now applies equally to the NHS.</p>
            <p>Part of the problem is due to the overprescribing of antibiotics by doctors and their availability off the shelf in some third world countries, but livestock producers consume 50 per cent of all antibiotics and the way they are used makes them even more culpable than prescription drugs.</p>
            <p>Superbugs have arrived and they are not going to go away - they are widespread in the environment and are even present in the intestines of many of our children. As antibiotic-resistant bugs have the ability to pass resistance on to other, unrelated bacteria, this worrying problem will continue to develop in unforeseen ways. </p>
            <p>Livestock producers have poisoned the environment at every level, even a microbiological level and we have no idea how devastating the eventual outcome will be. </p>
            <p>Just as they have started us down a road where infections are increasingly difficult to control because of antibiotics that no longer work, we are also presented with the spectre of new pandemic diseases to which we probably have little or no resistance. The current fear is over bird flu.</p>
            <p>Each species of animal used in intensive farming is invariably drawn from the same genetic stock. Selectively bred for quick growth and rapid weight gain they tend not to have good disease resistance. The problem is exacerbated by overcrowding and bad hygiene which leads to permanent stress, reducing the effectiveness of their immune system even further. Any disease which gains a foothold in one animal is therefore likely to rip through them all. Each new mass infection increases the likelihood of a bacteria or virus mutating into a form that can also infect humans.</p>
            <p>It is almost certainly these conditions that turned a relatively benign bird flu virus – H5N1 - into a virulent one. Whether H5N1 bird flu will mutate again into a form that can infect humans and potentially kill us <em>en masse</em> remains to be seen. Whether it does or not, there will be other new bacteria and viruses emerging and as the mass of farmed animals goes on increasing and the use of antibiotics goes on increasing it is likely that so will the risk.</p>
            <p>There are already new wasting diseases appearing specific to pigs and it is inevitable that there will be other novel diseases that infect humans also. We know what the government’s reaction is likely to be from the manner in which it handled mad cow disease (BSE) and its human equivalent, vCJD.</p>
            <p>Despite evidence to the contrary, it insisted that this new, incurable and highly-infectious disease would not infect humans, desperately placing the survival of the meat and dairy industries above human life.</p>
            <p>Of course they were wrong and it is only luck that comparatively few people have developed and died from vCJD and it has not become a mass epidemic – so far. <br>
  &nbsp;&nbsp;&nbsp; <br>
              A similar lack of concern for human life is revealed in the economic stranglehold which the developed nations have on the third world. Discriminatory import tariffs ensure that impoverished suppliers of cash crops remain that way. The crops they grow are largely high-protein fodder crops destined to feed the West’s animals.</p>
            <p>It is a huge industry largely controlled by multinational corporations (MNCs) and it is no coincidence that the countries which produce the bulk of these fodder crops are the most impoverished – those with crushing burdens of landlessness, food insecurity and starvation-related diseases.</p>
            <p>Published in 1980, the Brandt report attempted to chart a path to greater equality and fairer trade between nations with an emphasis on global democracy. At that time, MNCs controlled one-third of world trade. Since then their share has increased to two-thirds, helped by the privatisation of third world economies on the insistence of organisations such as the World Bank and International Monetary Fund (IMF).</p>
            <p>The World Trade Organisation (WTO) was spawned by the same vested interests and whatever its claims at moderating world trade, it is part of the holy trinity of global trade control. All three organisations are essentially instruments of the MNCs – conceived by them and acting in their interest and, hardly surprising, it is they which prosper at the expense of the world’s poor.</p>
            <p>It is farmed animals, their feed and drugs, pesticides, fungicides, herbicides and fertilisers which are largely the engines of this exploitation.&nbsp; </p>
            <p>Resources sold off by poor nations and largely bought by Western companies include energy, land and water – three elements vital to expansion of the livestock industry for both grazing and fodder production. The outcome has been even greater landlessness and food insecurity amongst the world’s poorest people.</p>
            <p>The violence which disfigures so many regions of the world is not unrelated to this destruction of the global environment and people’s essential support networks. The West’s addiction to animal protein carries much of the blame and directly contributes to starvation, disease, death and impoverishment of the world’s already most impoverished people.&nbsp;&nbsp;&nbsp;&nbsp; </p>
            <p>German ex-chancellor Willy Brant and his eminent team were obviously deeply moved by their research and warned that ‘business as usual’ was not an option for the West. Unless fundamental concepts of justice were introduced into relationships between the rich nations of the North and poor nations of the South, they said, we would witness conflict and bloodshed on an unprecedented scale.</p>
            <p>It has been business as usual and the Brandt team’s dire warnings appear to be coming true. A fundamental start to transforming this desperate situation would be the availability of land for the growing of crops for local consumption. It cannot happen while so much land is devoted to farmed animals for the West and they continue to devour the Earth more voraciously than any plague of locusts.</p>
            <p>I have included health and development issues in this environmental summary, along with antibiotic resistant superbugs and novel diseases, because they have a common cause; maybe not the only cause but certainly a major one - livestock.</p>
            <p>In human and environmental terms, all these disparate effects of livestock farming are profound. However, they are so interlinked that an improvement or reduction of risk in one area will have a powerful knock-on effect in all the other areas.</p>
            <p>Reduce livestock farming to save the global environment and fewer animals will suffer, less meat and dairy will be eaten and there will be a reduction in degenerative diseases, a drop in the use of chemicals, pesticides and fertilisers, a lower consumption of drugs and antibiotics, with a subsequent reduced risk of dangerous superbug mutations and novel diseases and a chance for the world’s most impoverished people to gain the fundamentals of life.</p>
            <p>This is such an extraordinarily powerful argument that it beggars belief that it is still having to be fought for. </p>
            <p>Dramatically reducing meat and dairy consumption is now a global necessity.</p>
            <p>So why was the Brandt report ignored and the Swann report and the WHO report and the China study…? And what are the prospects of this latest extraordinary report from the UN FAO being acted on? Very few, it would seem.</p>
            <p>Not an obvious person to quote but Sir Winston Churchill did have a way with words and this observation is apposite: “Men occasionally stumble over the truth, but most of them pick themselves up and hurry off as if nothing ever happened”. Even the UN FAO appears to be guilty of just this.</p>
            <p>Having spent the greater part of 400 pages outlining in extraordinary detail how farmed animals are destroying the Earth and backing up their claims with hundreds of references, the FAO then attempts to offer solutions which are patently unachievable and at no point say ‘reduce your meat consumption’ or ‘go vegetarian or preferably vegan’.</p>
            <p>Such advice would empower people, enabling them to take the solution into their own hands and make personal decisions which would instantly impact on a globe in crisis. Simply by saying ‘Not for me and not in my name’ they could slash not just their carbon footprint but all the other footprints which livestock producers have ensured are now indelibly trampled across almost every square meter of the Earth’s surface, below the surface, in the air and in the water. And all they have to do is change their diet!&nbsp; </p>
            <p>Instead of encouraging this most simple and effective of remedies, the UN FAO pretends that the consumption of livestock products, already causing global devastation and patently unsustainable, can continue simply by producers reducing the environmental impact made by each animal – slashing it by half. How they will do this is through ‘correcting for environmental externalities,’ ‘accelerating technological change,’ ‘reorientating extensive grazing towards provision of environmental services,’ and ‘encouraging efficiency through adequate market prices’.</p>
            <p>About the only recommendation that is comprehensible out of this and much more bureaucratic speak is that the market forces will provide part of the answer – the very forces that created the problem.</p>
            <p>The solutions it offers do not stand up to even cursory investigation as sensible answers to its central concerns, which are:</p>
            <p>“The livestock sector emerges as one of the top two or three most significant contributors to the most serious environmental problems, at every scale from local to global.”</p>
            <p>“Livestock’s contribution to environmental problems is on a massive scale…. The impact is so significant that it needs to be addressed with urgency.”</p>
            <p>“The findings of this report suggest that it should be a major policy focus when dealing with problems of land degradation, climate change, and air pollution, water shortage and water pollution and loss of biodiversity.”&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
            <p>Is the refusal to recommend the most simple, logical and easily achieved solution to these profound problems simply cowardice or an inevitable result of the report being co-ordinated by the Animal Production and Health Division of the FAO? It is fundamentally an organisation that represents the interests of the livestock sector and it seems there are limits on how hard it is prepared to bite the hand that feeds it.</p>
            <p>It says that to accommodate future growth in livestock production “we need to halve the impacts per unit of output to achieve a mere status quo,” a status quo that is devastating the planet! It does not say that we need to halve meat and dairy consumption but places the emphasis on a solution which is impossible to achieve. It is an abrogation of responsibility on a massive scale.</p>
            <p>Perhaps it is for this reason that it defines its role as finding “suitable technical solutions” but concedes that the ultimate decisions to address the damage done by livestock will be taken outside the agriculture sector. By this we presume it means government. If that is the case then we can anticipate procrastination, confusion, lack of action and a complete absence of joined-up thinking whoever is in power.</p>
            <p>Our political parties all profess to care about the environment but this does not translate into effective policy making. At the time of writing this report (November 2007) we have just come out of a phoney pre-election period in which each party slapped its environmental credentials on the table, boasting about whose was the biggest. So we know what they have in store.</p>
            <p>The Liberal Democrats declared their intention to research fodder that would reduce the emission of methane from ruminants. By how much they don’t know, but if it works at all it is likely to be marginal and will do nothing for the majority of ruminants across the globe that graze on rough land. It would, of course, also do nothing to reduce the impact of non-ruminant animals such as pigs and poultry or cut the nitrous oxides from excreta or CO2 from farm machinery or reduce livestock’s contribution to all the other global problems.</p>
            <p>The Conservatives chose to single out aircraft, taxing them to ensure they don’t fly with empty seats. The costs of fuel and airport charges already make flying with empty seats uneconomic and an additional tax is unlikely to offer any additional incentive.</p>
            <p>Their environmental adviser, Zac Goldsmith, ex-editor of the Ecologist, has his own and rather strange view on livestock production. As a non-executive director of the Weston A Price Foundation, he gives support to their position that we all need to eat meat and animal fat in quantity and that full fat dairy milk is a cure for many diseases.</p>
            <p>This, of course, stands a mountain of scientific research on its head and offers little hope that the Tories will produce sensible policies to tackle this global crisis.</p>
            <p>His first (short lived) suggestion was a tax on supermarket car parking so people would pay for driving there and contributing to CO2 emissions. They could, of course, then buy meat and dairy, which produces many times more greenhouse gases than cars, without any tax deterrent.&nbsp;&nbsp; </p>
            <p>Labour has also singled out aircraft as the unacceptable face of capitalism and proposes taxing them. At the same time it continues encouraging people to eat meat and dairy by paying out generous subsidies to farmers of around £3 billion annually, the lion’s share being for livestock and fodder production. This ensures that prices remain artificially low and helps to increase sales.</p>
            <p>Dairy farmers receive in the region of £80 million in subsidies while the Milk Development Council is joined at the hip to government, being sited within Defra, and is funded from public money with a remit to encourage milk drinking. The government also promotes the EU Butter for Manufacture Scheme, encouraging food manufacturers to use butter fat in their products in place of vegetable oil. And of course, it encourages and subsidises milk drinking in schools.</p>
            <p>Aircraft produce around three per cent of greenhouse gases, livestock 18 per cent, plus contributing to a raft of other problems. This is an extraordinary use of public money by any standard – encouraging the consumption of products which are at the heart of the nation’s health crisis and the world’s environmental crisis. It is unlikely to change whoever is in power in the foreseeable future.</p>
            <p>One of the most depressing aspects of livestock’s impact on the globe is the refusal (so far) of the large campaigning environmental organisations to take this on board. Both the Ecologist magazine and Friends of the Earth have encouraged meat and dairy consumption with cookery articles. Greenpeace has come the closest to calling for a move towards a plant-based diet but still fails to commit itself.</p>
            <p>The assumption is that so long as meat and dairy are free range and organic they tread lightly on the Earth and do no damage. These systems are certainly better for the animals involved but not necessarily for the environment.</p>
            <p>In fact, part of the FAO’s rather ludicrous solution is to encourage (half heartedly) further intensification of livestock farming as being less environmentally damaging than free range.</p>
            <p>Equally as inexplicable are the policy decisions of the large animal charities. The RSPB pleads for more agricultural land to be left untouched and available for birds to end the rapid decline of some species but never advocates cutting meat consumption and never criticises livestock, which demand 70 per cent of all agricultural land.</p>
            <p>A plant-based diet would require less than a quarter of the present agricultural land, allowing Britain’s wild areas to regenerate and the birds and animals that have long since been destroyed (as well as those in decline) to return. The new growth of shrubs and trees on such a large scale would constitute a massive carbon sink. </p>
            <p>The RSPCA was set up to safeguard the interests of domestic and wild animals and in 1994 formed its wholly-owned subsidiary, Freedom Food, a so-called meat and dairy assurance scheme. The RSPCA Freedom Food logo appears on both free range and factory farmed meat and its point-of-sale displays extol the virtues of its products, actively encouraging meat eating.</p>
            <p>These same animals are central to the destruction of ecosystems globally and are the single biggest cause of species loss. Through its promotion of meat and dairy, wild animals across the world are being decimated and pushed towards extinction, as are the ecosystems which support them. It is quite literally inexplicable for an organisation set up to protect them.</p>
            <p>The RSPCA would no doubt argue that it is pushing a particular brand of meat and not meat <em>per se</em>. This was an argument used by the tobacco lobby to retain cigarette advertising – and comprehensively dismissed. By associating itself with meat and dairy products the message it promotes is that everything is fine and there is no need to worry about eating meat and dairy.</p>
            <p>Everything is not fine and there is plenty to worry about.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
            <p>The simple truth is that the effects livestock are having on the planet dwarf in importance all the other campaigns of these groups combined. It cannot be an accident that they have avoided this most important of environmental subjects. Could it be that their refusal either to actively encourage a reduction in meat and dairy consumption or to promote a vegan diet is because it will be unpopular with members and might affect income? </p>
            <p>Whatever the reasons, it confirms yet again the privileged position that meat and dairy have been granted in our society and difficulties groups such as Viva! face in trying to raise awareness of the damage they do. In the many TV and radio debates we have had with the farming industry there has been no acknowledgement of the problems let alone agreement on how to deal with them. </p>
            <p>The whole approach begins to feel like an episode from the TV comedy series Fawlty Towers, entitled: “Don’t mention the meat!”</p>
            <p>Unless this changes rapidly, the future looks exceedingly grim. There are barely any politicians who have exhibited the kind of political courage that will be necessary to tackle meat and dairy consumption as the threat they pose to society.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              One inescapable fact from the FAO report is that we have essentially run out of land for livestock production and yet it is forecast to go on increasing – dramatically. The land to accommodate this growth will be from the further clearing of yet more ecosystems such as rainforests or by increasing yields through greater intensification of existing production with massive chemical inputs. The result of either will be disastrous.</p>
            <p>Yet at the same time, governments worldwide are encouraging the development of biofuels as alternative sources of energy – wheat, palm oil, willow and so on. Without curbing livestock production this is clearly unsustainable because there is simply not sufficient land for both. Sadly, the felling of Indonesian forests to provide palm oil plantations is a clear indication of the direction in which we’re heading.</p>
            <p>Further intensification of arable farming will accelerate the relentless degradation of land, resulting in loss of soil fertility and the release of CO2 it holds captive, spurring more global warming. It will also reduce the planet’s ability to absorb CO2 in the future. The same is true for rainforest clearance – producing large amounts of CO2 from slash and burn and reducing the amount of new growth, which absorbs CO2.</p>
            <p>There is no longer any serious scientific argument that sea levels won’t rise as global warming continues. The only question remaining is by how much. The humanitarian catastrophe this will create will be matched by widespread conflict as millions of displaced people move on to other’s land and the total of land available to support life is reduced. </p>
            <p>There are no policies by any of the leading political parties to address these profoundly disturbing events and it is clear who will have first call on the land remaining.</p>
            <p>The huge, multinational pharmaceutical corporations are courted and feted and we are increasingly warned that if animal welfare organisations insist on exposing their maltreatment of animals or demanding higher standards, these giants will relocate abroad. Their existence is presented as essential to our survival when they are major contributors to our potential destruction. </p>
            <p>The fact is, they have been instrumental in turning the health service into a sickness service based on prescribing a pill for every ailment. Only two per cent of the health budget is spent on prevention – for major killer diseases which are largely diet and lifestyle related and therefore eminently preventable.</p>
            <p>The government’s reaction to the introduction of their genetically modified organisms (GMOs) typifies the privileged position the pharmaceutical giants hold. It was gung ho about them and even appointed a proponent of GMOs in the form of Lord Sainsbury as Science Minister. His role was clearly to usher in these unknown new life forms and it was only the reaction of the public which stopped it.</p>
            <p>The determination to introduce them continues unabated but more stealthily. The billions spent on research WILL be repaid. Many people have objected but few have, in my view, identified the real reason for GMOs. The answer is inextricably linked to livestock production and has nothing to do with feeding the world’s impoverished – in fact their widespread use will ensure a rapid growth in the number of impoverished people.</p>
            <p>The concentration of 80 per cent of the world’s livestock into intensive factory farms has proved a bonanza for the $600 billion pharmaceutical industry, which has encouraged and welcomed it and grown rich on the results. Some 55 billion animals are slaughtered annually at the moment (but increasing) and this burgeoning animal population has to be fed, mostly with the products of intensive agriculture.</p>
            <p>Land is pushed beyond its natural ability with artificial fertilisers and a battery of pesticides, fungicides and herbicides – products of the pharmaceutical industry! The animals themselves cannot survive without a similar onslaught of medications, antibiotics and pesticides. And when humans eat the resulting animal products they develop the degenerative diseases that pharmaceutical companies pretend to control with a dazzling selection of medications. A pill for every ill! It is a wonderfully brilliant circular scam that eclipses pyramid selling in its ingenuity. </p>
            <p>In order to maintain their phenomenal growth rate it is essential that this industry spreads intensive farming across the world. It is their goose which lays golden eggs. The theory is that herbicide-resistant GMO’s will enable them to eliminate all other plant forms from agricultural land and squeeze every last drop of production from it. Another chapter in the unfolding environmental nightmare.</p>
            <p>Without increased fodder supplies there are limits on how far and fast factory farming can spread and a subsequent limit of the pharmaceutical companies’ profitability. They also need land and water and it is no accident that the policy of privatisation for developing countries promoted by the IMF and World Bank is increasingly placing both in their hands.</p>
            <p>It is also no accident that the first major GMO crops introduced are essentially fodder crops – maize, wheat, soya, rape seed. And as global food output reduces, as is already happening with wheat, it will be the diseased and dejected but profitable caged animals who take precedence and the very unprofitable, impoverished people who will go without.</p>
            <p>Any doubts about this cynicism should be dispelled by the action of some pharmaceutical companies towards South Africa’s attempt to supply cheap generic drugs to its AIDS patients. They were fought all the way by the patent holders despite having one of the worst AIDS problems in the world, an epidemic which is devastating the country and causing unbelievable suffering. Even with the spotlight on them, the companies initially chose profitability over compassion.</p>
            <p>They have flooded the wealthy Western markets with a dazzling array of medications to treat every real and imagined ailment but have almost entirely ignored the devastating diseases that ravage populations in the third world. There is no profit in poverty – and so it will be in the scramble to control diminishing food supplies. Feed for animals will increasingly take precedence over food for people.</p>
            <p>Again meat is publicly let off the hook and Lenny Henry in his sparkly suit, development agencies and other wearers of red noses make no reference to it. Don’t mention the meat!&nbsp;&nbsp; </p>
            <p>The scale of environmental decline is profound yet politicians have reduced it to ludicrous sound bites that pretend to offer action but are meaningless.&nbsp; ‘Polluter pays’ is a classic example.</p>
            <p>This implies that there are two groups of people in Britain – those who pollute and those who don’t. Presumably, those who drive four trax and fly frequently are the polluters whilst the rest of us are non polluters.</p>
            <p>We are all polluters on a massive scale but none more so than those who regard meat, fish and dairy products as central to their diet.</p>
            <p>However, these products are, in many ways, no different to all the other products which result from a free market and to attempt to curb their use would provoke howls of protest from very powerful vested interests.</p>
            <p>The fact that they are being consumed at an unsustainable rate takes second place to maintaining the concept of a free market, just as it does with oil and dozens of other minerals and metals – and even water. This is the dilemma which confronts almost every government in the world and which they are impotent to answer.</p>
            <p>It is a problem exposed by the UN Environment Programme which maintains that to continue consuming at the present rate we will need two additional planets to exploit. The mathematics are blindingly simple – we cannot continue with a policy of constant growth, consuming the worlds resources at an ever-increasing rate, when those resources are finite and the process of consuming them has the potential to destroy us!</p>
            <p>Growth is the bed rock of consumerism and to end it arbitrarily will result in a global economic collapse, not to end it will result in a global ecological and environmental collapse. The former can be managed by acknowledging the dilemma quickly and planning for it by dramatically reducing our impact on the globe - essentially transforming the way society functions and ending constant growth as its driving force.</p>
            <p>The latter is likely to wipe us out as a species and many other species along with us. </p>
            <p>Look around the globe and the portents are not good. Rather than planning for the inevitable there is a desperate attempt to prolong the reckoning as long as possible through ‘me-first’ foreign polices.</p>
            <p>There is a scramble for the remaining resources, with so-called democratic Western governments pursuing imperialist wars for oil in Iraq and Afghanistan – the gateway to several, oil-rich smaller countries. We stand idly by as people are cleared from Darfur to make oil exploration trouble free. We are courting some of the most odious regimes across the Middle East and in Uzbekistan and Burma and blinding ourselves to their appalling human rights record – in return for oil and gas. Battle lines for conflicts over ground water, rivers and minerals are already being drawn.&nbsp; </p>
            <p>One country which illustrates the confusion and hypocrisy better than any other is China. The West has virtually subcontracted much of its manufacturing base to this authoritarian regime and eagerly accepts the mountains of plastic and cheap products that it produces. At the same time, we wring our hands over its environmental record and shake our heads in despair at the pollution they are creating – mostly on our behalf – and, at the same time, encourage their introduction of large-scale development of yet more factory farming systems.</p>
            <p>It is clear that the government’s <em>laissez faire</em> attitude to the industrial sector applies equally to the meat and dairy industries. These are as much industrial products as cheap power tools or plastic Power Rangers, only more damaging. Even if it wanted to act on the latest desperate warnings, the lobbying power of the agricultural, pharmaceutical, manufacturing and food marketing sectors of the economy will ensure behind the scenes arm twisting on an intergalactic scale.</p>
            <p>Part of the popular media has largely decided that global warming is a sham and encourages every half-baked and unscientific denial. The Daily Mail has made climate denial editorial policy. You can imagine the outcry these titles will whip up if our ‘brave farmers’ are threatened. Newspapers and magazines are, of course, an integral part of the consumer society and depend upon mass advertising for a large chunk of their revenue, much of it for meat, dairy and leather products.</p>
            <p>We are therefore facing a watershed in the way our society is governed and our attitude to the planet on which we live. The policy decisions that are so vitally needed may be a long, long way off. With the Intergovernmental Panel on Climate Change (IPCC) warning that as far as global warming is concerned it may already be too late, action is needed now not a decade or two down the line.</p>
            <p>Fortunately, you can exercise your freedom of choice and have an immediate impact on the world. Give up meat, fish and dairy now, adopt a vegan diet and reduce the impact of global warming, end the mass suffering of animals, slow the advance of antibiotic-resistant superbugs, end your part in the clearing of forests, the spread of deserts, the loss of species and the waste of fresh water.</p>
            <p>It is an extraordinarily empowering decision and the only tragedy is that there are so few voices prepared to advocate it.</p>
            <p>The one thing we cannot do is allow market forces to determine what happens. Even if you believe that markets work, they will not and cannot in this situation. Central to their working is their ability to adapt and change as circumstances develop or problems arise.</p>
            <p>With the environment, and global warming in particular, the major problems do not become apparent until long after it is too late to do anything about them. Once global warming passes the tipping point, enters into positive feedback and becomes unstoppable, which the IPCC thinks may already have happened, our free marketeers will be impotent.</p>
            <p>Make no mistake, effectively tackling environmental decline is going to result in a battle that pits ordinary, concerned people against huge vested interests and weak governments. In fact, it has already started!</p>
            <h2 align="right"><a href="/campaigns/hot/dietofdisaster/page2.php">Next &gt;</a></h2>
          <!-- InstanceEndEditable -->
            <div align="center" class="smalltext"><b>Viva!</b> Vegetarians International Voice for 
              Animals<br>
              8 York Court, Wilder Street, Bristol BS2 8QH, UK<br>
              T: 0117 944 1000 F: 0117 924 4646 E: <a href="mailto:info@viva.org.uk">info@viva.org.uk</a></div>
          </div></td>
        <td width="15" class="bgright">&nbsp;</td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td><img src="/campaigns/hot/images/bgbottom.jpg" alt="" width="754" height="41"></td>
  </tr>
</table>
</body>
<!-- InstanceEnd --></html>
