<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><!-- InstanceBegin template="/Templates/hotsite.dwt.php" codeOutsideHTMLIsLocked="false" -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- InstanceBeginEditable name="doctitle" -->
<title>Viva! HOT! Campaign</title>
<!-- InstanceEndEditable -->
<link href="/campaigns/hot/includes/styles.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="/campaigns/hot/includes/ddtabmenu.css">
<script type="text/javascript" src="/campaigns/hot/includes/ddtabmenu.js">

/***********************************************
* DD Tab Menu script- © Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
***********************************************/

</script>
<script type="text/javascript">

//SYNTAX: ddtabmenu.definemenu("tab_menu_id", integer OR "auto")
ddtabmenu.definemenu("ddtabs1", "auto") //initialize Tab Menu #1 with 1st tab selected
</script>
<!-- InstanceBeginEditable name="head" --><!-- InstanceEndEditable -->
</head>

<body>
<table width="754" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
        <tr valign="top">
          <td width="41" height="41" bgcolor="#990099" class="bgleft"><img src="/campaigns/hot/images/bgtl.jpg" alt="" width="41" height="41"></td>
          <td class="bgtop"><?php include '../includes/menu.php'; ?></td>
          <td width="41" height="41" class="bgright"><img src="/campaigns/hot/images/bgtr.jpg" alt="" width="41" height="41"></td>
        </tr>
      </table>
   </td>
  </tr>
  <tr>
    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="15" class="bgleft">&nbsp;</td>
        <td valign="top" bgcolor="#FFFFFF"><!-- InstanceBeginEditable name="banner" --><img src="/campaigns/hot/images/banner05.jpg" alt="" width="724" height="249"><!-- InstanceEndEditable -->
          <div id="content"><!-- InstanceBeginEditable name="content" -->
            <p align="center"><strong>Contents</strong>: <br>
                <a href="index.php">Overview</a> | <a href="page2.php">Global Warming</a> | <a href="page3.php">Deforestation and Loss of Biodiversity</a> | <a href="page4.php">Overuse of Fresh Water</a> | <a href="page5.php">Destruction of the Oceans</a> | <a href="page6.php">Fish Farming</a> | <a href="page7.php">Pollution: <span class="smalltext">Antibiotic Pollution</span></a><span class="smalltext"> | <a href="page8.php">Chemical Pollution</a> | <a href="page9.php">Heavy Metal Pollution</a> | <a href="page9.php">Pesticide Pollution</a></span> | <a href="page9a.php">Desertification</a> | <a href="page11.php">Bird Flu</a> | <a href="page11.php">Health</a> | <a href="page12.php">References</a></p>
            <h1><strong>Global Warming</strong></h1>
            <p>The processes through which greenhouse gases trap heat and warm the Earth are now well established. That it is human activity which carries the blame is also well established by an almost unique scientific consensus that has probably never been seen in living memory. </p>
            <p>Former US vice president Al Gore, in his Nobel Peace Prize-winning film, An Inconvenient Truth spelt out the extent of that consensus – published scientific papers that establish human responsibility for the problem: almost 1,000. Scientific papers showing it’s got nothing to do with humanity: zero. US media reports on the same issue show a very different slant: 68 per cent in favour of global warming being a natural phenomenon and 32 per cent supporting the scientific consensus (Gore, 2006),.</p>
            <p>The ratio may not be quite so wide in the UK but there is still nothing like balance in the debate. Climate change denial, or at least humans’ responsibility for it, has become editorial policy in the Daily Mail, including its science editor. Some other papers and the BBC adopt an ‘even-handed’ approach, providing equal space for denial and therefore presenting the debate as one which is evenly divided in terms of scientific opinion.</p>
            <p>Incredibly, when the UN FAO published its report in 2006, establishing that livestock are not only the second largest source of greenhouse gases but central to every other environmental catastrophe, it was virtually ignored in Britain. What should have been an Earth-shattering report was carried by three titles, two of them agricultural papers.</p>
            <p>The delicate nature of the Earth’s atmosphere was spelt out:</p>
            <p>“The atmosphere is fundamental to life on Earth. Besides providing the air we breathe it regulates temperature, distributes water, it is part of the key processes such as the carbon, nitrogen and oxygen cycles and it protects life from harmful radiation. These functions are orchestrated in a fragile, dynamic equilibrium by complex physics and chemistry.”</p>
            <p>This ‘fragile and dynamic equilibrium’ is being altered and we can only guess at the outcome but it will not be beneficial. Livestock and industrial fishing carry a large share of the blame and constitute the second largest source of greenhouse gases.</p>
            <p>The gas most damaging for the environment is CO2 because of the quantities that are produced. The second most damaging is methane, 21 times more effective at trapping heat than CO2 and which remains in the atmosphere for nine to 15 years. Nitrous oxide is the third most damaging, has 296 times more global warming potential than CO2 and retains its effect for 114 years. </p>
            <p>Livestock (and the processes to feed, transport, kill and manufacture meat and dairy) are responsible for considerable amounts of all three gases. For example the UN FAO states: </p>
            <ul type="disc">
              <li>A large share of the world’s crop production      is fed to animals. Nitrogen fertilizer is applied to much of the cropland.      Fossil fuel used in the manufacturing of fertilizer may emit 41 million      tonnes of CO2 per year. </li>
              <li>Livestock on farm use of energy (eg for      pesticides, diesel, electricity) causes even greater emissions – 90 millions      tonnes of CO2 per year. </li>
              <li>Livestock related land use changes (such as      forest clearance, biomass burning) may emit an astonishing 2.4 billion      tonnes of CO2 per year.</li>
              <li>Releases from livestock-induced      desertification may total 100 million tonnes of CO2 per year.</li>
              <li>Methane from enteric fermention: 86 million      tonnes per year.</li>
              <li>Methane from animal manure: 18 million tonnes      per year.</li>
              <li>Livestock contribute 65 per cent of global      human-related nitrous oxide emissions – the largest cause being from both      applied and deposited manure. </li>
            </ul>
            <p>&nbsp;</p>
            <p>The UN FAO estimates that livestock are responsible for 18 per cent of global warming gases compared to 13.5 per cent for all the world’s different forms of transport combined. Interestingly, the sector the UK government has chosen to pillory is air travel, responsible for just three per cent of global warming gases. Again, its special relationship with livestock producers results in inertia when immediate and far-reaching action is demanded.</p>
            <p>Concentrations of CO2 are higher than at any time in the last 650,000 years, methane has doubled since pre-industrial days and average temperatures have increased by 0.8 deg C (2005). What international attempts have been made to address the issue at Cancun and Kyoto have been abject failures as no country is prepared to risk its industrial growth in order to seriously address global warming (Guardian, 2007) . Individual organisations are, however, beginning to find their voices.&nbsp; </p>
            <p>&nbsp;</p>
            <p>In 2005, the University of Chicago’s department of geophysical sciences examined the amount of energy used by different food industries. In addition to what the animals produced themselves, the amount of fossil fuel energy used to grow fodder for farmed animals and in processing is considerable; as is the nitrous oxide from slurry lagoons. It found that the worst offender is red meat in terms of the amount of greenhouse gases produced; followed by fish (largely due to industrial methods of catching), then dairy, then poultry. Vegan diets are the least harmful by far.&nbsp;If someone ate 26 per cent of calories from red meats then they would contribute 2.5 tonnes more of carbon dioxide equivalent per year than a vegan - more than the average output of many types of car over the same time span (Eshel, 2006).</p>
            <p>Their conclusion: “However close you can be to a vegan diet and further from the mean American diet, the better you are for the planet”.</p>
            <p>The Washington-based World Watch Institute has also been forthright in interpreting its research:</p>
            <p>“As environmental science has advanced, it has become apparent that the human appetite for animal flesh is a driving force behind virtually every major category of environmental damage now threatening the human future” (World Watch 2004). &nbsp;</p>
            <p>Earthsave International has done its own research and is equally vocal about the damaging effect farmed animals are having on climate change. It maintains that animal agriculture is responsible for over 100 million tonnes of methane a year – 85 per cent from digestion and 15 per cent from slurry lagoons.&nbsp; </p>
            <p>Its conclusions are: “The best way to reduce global warming is to reduce or eliminate our consumption of animal products. Simply by going vegetarian (or, strictly speaking, vegan), we can eliminate one of the major sources of methane” (Mohr, 2005).<br>
  &nbsp;&nbsp;&nbsp; <br>
              As developing countries such as China emulate the West’s addiction to animal products, the Profetas study, set up by the three Dutch universities of Twente, Waganingen and VUA maintain that the situation is accelerating away from us. The 19 academics involved maintain that “this trend must be reversed on a global scale”. We should all be looking to make the transition from meat protein to vegetable protein alternatives (novel protein foods) based on such plants as soya. Doing so will positively affect everything from sustainable energy and water use to biodiversity, human health and animal welfare, they maintain (Aiking, 2006).</p>
            <p>A joint study by Amsterdam University and Loma Linda University, California attempted to assess the benefit of switching from a meat protein to a vegetable protein diet on a variety of inputs, including energy. On every count, meat dairy and fish consumed more energy and made a greater negative impact on the globe than vegetable protein.</p>
            <p>On land requirement, they established that on average, 10g of vegetable protein was needed to generate 1g of animal protein but the rate varied with different animals. For broiler chicken production the conversion rate was 16 per cent (nearly six to one in favour of vegetable protein); on pork it was 9 per cent (11 to one) and beef, six per cent (17 to 1).</p>
            <p>In the comparison between meat production and soya-based vegetable protein production, this translates into meat requiring between six and 17 times more land. On fossil fuel energy use the difference globally is a staggering two-and-a-half times to 50 times greater for meat while in Europe it is between six and 20 times greater.</p>
            <p>The use of cheese made from lupine (white lupin seeds/beans) was compared with cow’s milk cheese but only for land use and pollutants. The environmental burden of the cow’s milk cheese was 19 to 21 times greater than vegetable-based cheese.</p>
            <p>The study also considered the energy demands of fish eating and established that trawling, the most common method of fishing in Western Europe for bottom-feeding fish, required 3.4 litres of fuel oil per kilogram of fish. This translates into an energy demand&nbsp; approximately 14 times greater than for vegetable protein.</p>
            <p>For mid-water gill net fishing the demand was lower, at 0.4 litres of oil per kilogram of fish and an overall energy demand 65 per cent greater than for vegetable protein. However, when processing is added into the equation the overall demand on fossil fuels is between 20 and 44 times greater for fish than for vegetable protein </p>
            <p>The rapid development of fish farming – aquaculture – is sometimes offered as a solution to fishing and diminishing stocks. The study found that in terms of pesticide and fungicide use and the release of damaging nutrients into the environment there was little difference between fish farming and other forms of intensive animal farming. It goes on to say that the farming of carnivorous fish (most farmed fish are carnivorous) “probably poses a relatively heavy environmental burden.” The report goes on:</p>
            <p>“Many scientists and even policymakers have begun to question the sustainability of agriculture as practised today. Particular scepticism has been directed at supporting the increased demand for animal products…. Throughout the world there appears to be a direct link between dietary preferences, agricultural production and environmental degradation.”</p>
            <p>It continues:</p>
            <p>“Encouraging individuals to eat more efficiently, consuming less meat and more plant-based foods, may be one of the measures that will lead to increased sustainability and reduced environmental costs of food” (Reinjnders, 2003).</p>
            <p>The findings of this particular study have been reflected by many other studies over a decade or more with similar results to a greater or lesser degree.</p>
            <p>Soya has become both a demon and a saint.&nbsp; Its demonic status is the damage its production for animal feed causes to the environment while its saintly status is the potential it has to feed the world efficiently and sustainably. It has become fashionable to blame vegetarians and vegans for deforestation because of their consumption of soya.</p>
            <p>In fact, 80 per cent of soya is fed to animals and the bulk of the remainder is used in mainstream food production as padding for such things as meat pies and other processed products. Only a tiny proportion is currently used for the manufacture of mock meat vegetable protein.</p>
            <p>Despite this there is a sustained and growing attack on soya from pseudo scientific sources, presenting it as a serious health risk to humans because of its plant ‘oestrogen’ content. The Vegetarian &amp; Vegan Foundation recently reviewed the science on soya and found no adverse effects – in fact it is a valuable and wholesome addition to the diet, evidenced by the fact that 25 per cent of US children have been fed soya infant formula&nbsp; for almost 40 years and exhibit no adverse effects (Butler, 2006).</p>
            <p>It is perhaps not surprising that the main source of these supposed warnings is an organisation that declares that humans need to eat meat and saturated animal fat and full-cream milk in order to be healthy. Just another member of the denial brigade but adopting different tactics (WAPF, 2007).&nbsp;&nbsp;&nbsp;&nbsp; </p>
            <p>The pressure that livestock exert on the environment is extreme and patently unsustainable. In terms of greenhouse gases, it is not just the emissions from production and processing that are of concern but the fact that livestock reduce the capacity of the planet to absorb CO2.</p>
            <p>One of the greatest CO2 sinks is soil itself and as the hooves and overgrazing of animals degrade it so it releases the C02 it holds captive. That soil then loses its ability to absorb further CO2 from the environment. Similarly with the loss of forests; not only are huge quantities of CO2 released by the slash and burn practices of deforestation, the loss of vegetation ensures that there is a reduction in new growth to absorb future emissions of C02 (UN FAO, 2006).</p>
            <p>The results are almost farcical – governments wringing their hands about climate change while increasing their country’s emissions and supporting policies and practices that reduce the planet’s ability to absorb CO2. The situation is set to worsen as raised sea levels inevitably flood large areas of fertile land, both reducing the size of the carbon sink and reducing agricultural output.</p>
            <p>Evidence of a reducing ability to absorb CO2 is already there, according to the Global Climate Project in Canberra. Its report claims that about half the CO2 emissions resulting from human activity have historically been absorbed by these natural sinks on land and in the oceans. Fifty years ago, for every tonne of CO2 produced, 600 kg was absorbed but in 2006 it was only 550 kg and reducing (Independent 2007).</p>
            <p>Corinne Le Quere, climate researcher with the British Antarctic Survey in Cambridge explained that stronger winds in the Southern Ocean caused by global warming and the loss of the ozone layer has resulted in more dissolved carbon dioxide in the deep sea being brought to the surface and consequently less carbon dioxide being absorbed from the atmosphere. She said:</p>
            <p>“This is incredibly important. It is bad news because we can’t do much about these natural carbon sinks. Things are happening much faster than we expected” (Independent, 2007).&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
            <p>The reason why more and more academics are being galvanised into action is because the scientific models which predict what’s likely to happen with global warming are clearly wrong – it is all happening far, far quicker than anyone believed - three-times faster than predicted in the 1990s with sea levels rising twice as fast as predicted, according a study by the US National Academy of Sciences (Independent, 2007).</p>
            <p>Professor David King, scientific adviser to the UK government, says that levels of CO2 in the atmosphere are “higher than we’ve seen for over a million years, possibly 30 million years” (Telegraph, 2006).</p>
            <p>The situation is compounded by the effects of Kyoto, the international agreement that was supposed to save us with such things as carbon trading and carbon credits. It has produced incompetence, abuse, few savings but huge profits, according to a Guardian investigation (Guardian, 2007). </p>
            <p>Two studies in the science journal <em>Nature </em>claim that glaciers and arctic ice sheets are melting so fast that we could be heading for catastrophic rises in sea levels – several metres by the end of the century (Raper 2006). </p>
            <p>The prestigious publication <em>Proceedings of the National Academy of Science</em> has also expressed serious concern. Its major worry is that once average temperatures rise by 3 deg C – and that is well within the range predicted - atmospheric CO2 that is currently absorbed by plants will be outweighed by the CO2 produced from the soil in which they stand as a result of organic decomposition (Joughin, 2004).</p>
            <p>This is one of several tipping points, the trigger for positive feedback or the point of no return – phrases that are being increasingly used but all amount to the same thing – global warming will become unstoppable, with unknown consequences. </p>
            <p>A report in <em>New Scientist</em> revealed that the vast permafrost peat bogs of Siberia are no longer perma and have started to thaw. Methane is a gas 21 times more damaging than CO2 and over the coming decades, Siberia is likely to emit 70 billion tons of methane. </p>
            <p>The outcome is likely to be that global temperatures will rise even faster and higher than the current revised estimates and defrost more tundra, which will release more methane in another positive feedback scenario (New Scientist, 2005).</p>
            <p>“When you start messing around with these natural systems”, says David Viner, senior scientist at the Climate Research Unit at the University of East Anglia, “you can end up in a situation where it is unstoppable. There are no brakes you can apply.”</p>
            <p>The situation is likely to be made worse by the warming of the Arctic Ocean, triggering even greater methane releases from the sea bed. According to Michael Meacher, one-time Labour environment minister, this process could make the planet uninhabitable for humans. Such candour helped to lose him his job (Ecologist, 2007).&nbsp;&nbsp; </p>
            <p>A far-sighted report by European meat industry vets written in 1990 had already said the unsayable: “Nature might be totally unpredictable if knocked out of balance. We are not able to destroy the Earth but we might change the climate in an unpredictable direction – at worst endangering our survival as a species” (Smulders, 1991).</p>
            <p>Professor Peter Cox of Exeter University reported to the Royal Geographical Society in 2007 that this tipping point could be reached as early as 2050(Cox P). </p>
            <p>In the face of all this, the role of the US government has been reprehensible both in originally refusing to admit climate change and attempting to undermine the science behind it. Why else would president Bush have appointed Philip Cooney – an oil industry lobbyist without a science degree to his name - as head of his environment office? His contribution to the problem was to rewrite the warning papers of government scientists, altering words such as ‘will’ to ‘may’. </p>
            <p>When he was eventually caught and resigned, he walked into a job at oil giant Exxon Mobil the very next day. Pure coincidence, of course, that Exxon generously funds almost the entire denial industry. If ex-vice president Al Gore hadn’t exposed this in his Nobel Peace Prize-winning film, <em>An Inconvenient Truth</em>, we would probably have remained ignorant. </p>
            <p>Another step taken by Bush in 2007 was to invite 16 major economies to form a climate change forum essentially in opposition to the UN (Independent, 2007). It evoked rare criticism from the UN secretary general Ban Ki-moon. He told a meeting of world leaders and scientists that the&nbsp; effort to control climate change … “will succeed or fail based on the strength of leadership and commitment displayed by the people in this hall.”</p>
            <p>The US is responsible for 25 per cent of the world’s pollution and greenhouse gases and has shown no strength, leadership or commitment. Its refusal to agree caps on emissions, not to approve any policy that might impinge upon the profitability of US industry and to actively attempt to undermine the UN Intergovernmental Panel on Climate Change (IPCC and joint winners of the Nobel Peace Prize with Al Gore) illustrates that there is little hope of the global action required to avoid catastrophe.</p>
            <p>The urgent need for action is illustrated by the IPCC, despite having been previously accused of watering down the science on climate change (New Scientist, 2007). Prof Martin Perry, a senior Meteorological Office scientist and co-chairman of the IPCC committee, spelt out a stark warning when presenting the committee’s latest report to the Royal Geographical Society in London in September 2007.</p>
            <p>He said that a rise of two degrees centigrade in global temperatures – the point considered to be the threshold for catastrophic climate change – is now very unlikely to be avoided. In UN-speak that is interpreted as there being between one and 10 per cent chance of averting disaster.</p>
            <p>“Even if we agree a cap at two degrees, there is a stock of major impacts out there already … You cannot mitigate yourself out of this problem… The choice is between a damaged world or a future with a seriously damaged world.”</p>
            <p>This damage will include between 350 and 600 million people in Africa suffering water shortages; a fall in agricultural yields of up to one half; and a spread of eight per cent in arid areas. In Asia, a billion people will suffer water shortages as the Himalayan glaciers melt and crops yields will fall. In Latin America 77 million people will lack water and tropical rainforests will become Savannah. Of course, storms, tempests and widescale flooding will feature everywhere.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              It is against this background that the denial industry flourishes, with the encouragement of the US government. There is perverse logic to the world’s most profitable oil company denying climate change but tobacco giant Philip Morris is also involved, as George Monbiot points out in his book <em>Heat</em> (Allen Lane). Why? Because the belief is that if you can undermine sound science on one front, you weaken it on all fronts! </p>
            <p>As well as having powerful political patronage, a diverse range of corporations have joined together to rubbish scientific research through puppet organisations such as the Advancement of Sound Science Coalition. In Philip Morris’s case it is to throw doubt on the claim that passive smoking kills but alongside them are biotech companies who promote GM foods and the nuclear industry. Together, their aim is to reduce ‘over regulation’, promote ‘sound science’ and discredit ‘junk science’. By junk science they mean anything which threatens their profits and by sound science they mean their own pseudo-scientific denials (Monbiot, 2007).</p>
            <p>Some sections of the media are willing accomplices in this and typical of its coverage was an article in 2007 in the Daily Mail headlined, ‘Global Warming? It’s natural, say experts’. The ‘experts’ turned out to be activists from the Hudson Institute and not climate scientists.</p>
            <p>The Hudson Institute is firmly aligned to big business, closely associated with the Bush neo-conservative clique which has fought bitterly to deny climate change and refused to act to reduce it. Herman Khan, the founder, actively encouraged the idea of winnable nuclear war. These and similar organisations have huge resources, enormous political clout and have successfully confused the debate on climate change. And there is much more to come from them.</p>
            <p>Governments appear to be complicit in this lack of action. When Viva! wrote to Defra (Department for Environment, Food and Rural Affairs) to ask what action they intended to take as a result of the UN FAO report, its Customer Contact Unit replied. It said that eating meat and dairy was a personal choice and that methane from landfill sites was part of the problem. If vegetarians cut down their vegetable waste it would help reduce climate change!</p>
            <p>In the past Viva! has written at length about Australia’s imbecilic policy of allowing 180 million alien cattle and sheep to destroy its fragile environment. The pay back is that the country is suffering the worst drought on record and the farmers who have resisted all curbs on livestock production now face possible devastation (Independent, 2007). And drought has reappeared in the US, the worst since the great depression (Independent, 2007).</p>
            <p>Hardly surprising, six scientists from some of the US’s leading scientific institutions have delivered an unambiguous warning that civilisation itself is threatened by global warming (Hansen, 2007).&nbsp; </p>
            <p>Writing independently in <em>Physics World</em> magazine, physicist Alan Calverd calls for a veggie world because of emissions. He claims that getting rid of meat animals is not only the easiest way to reduce greenhouse gases but would also free up huge tracts of farmland for growing biofuels, which would further reduce carbon dioxide emissions.</p>
            <p>The dominance and inviolability of cattle farming is summed up by the Bush administration’s policy decision to allow farmers greater grazing access to the 160 million acres of public land. It based its decision on a report from the Bureau of Land Management (BLM) which concluded that grazing would be beneficial. Two retired scientists who helped compile the report have recently spoken out. </p>
            <p>“This is a whitewash”, said Erick Campbell, a Nevada state biologist who looked at wildlife impact. “They took all our science and reversed it 180 degrees. They rewrote everything. It’s a crime!” Hydrologist Bill Brookes considered the impact on water and is just as unhappy: “Everything I wrote was totally rewritten. Instead of saying that, in the long term, grazing will create problems, it now says it’s the greatest thing since sliced bread” (Scientific Integrity, 2006).</p>
            <p>The bald statistics on greenhouse emissions from animal agriculture are bad enough – at 18 per cent, the second largest source. But the true figure is greater than this. The destruction of biomass and the degradation of soil impair the planet’s ability to absorb future CO2 (UN FAO, 2006).. And to these concerns need to be added the carbon emissions from fishing. </p>
            <p>One of the most effective but least reported action anyone can take to reduce their own carbon footprint is to change their diet to one based on plants: to go vegan.</p>
            It has other profound advantages, too. It reduces their impact on desertification, deforestation, water and air pollution and the other issues covered in this report. 
            <h2 align="right"><a href="/campaigns/hot/dietofdisaster/page3.php">Next &gt;</a></h2>
          <!-- InstanceEndEditable -->
            <div align="center" class="smalltext"><b>Viva!</b> Vegetarians International Voice for 
              Animals<br>
              8 York Court, Wilder Street, Bristol BS2 8QH, UK<br>
              T: 0117 944 1000 F: 0117 924 4646 E: <a href="mailto:info@viva.org.uk">info@viva.org.uk</a></div>
          </div></td>
        <td width="15" class="bgright">&nbsp;</td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td><img src="/campaigns/hot/images/bgbottom.jpg" alt="" width="754" height="41"></td>
  </tr>
</table>
</body>
<!-- InstanceEnd --></html>
